import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/src/components/layout/Header";
import Footer from "@/src/components/layout/Footer";
import { getDictionary, Locale } from "@/src/lib/dictionaries";
import { Suspense } from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "CarpNotes",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return [{ lang: "en" }, { lang: "ua" }];
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode,
    params: Promise<{ lang: string }>;
}>) {
    const resolvedParams = await params;
    const lang = resolvedParams.lang as Locale;
    const localeDictionary = await getDictionary(lang);

    return (
        <html lang={lang}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} antialiased`}
            >
                <Suspense>
                    <Header
                        locale={lang}
                        headerDict={localeDictionary.header}
                    />
                </Suspense>
                {children}
                <Footer />
            </body>
        </html>
    );
}
